replicaCount: 1
shards: 1
persistence:
  size: 10Gi
zookeeper:
  replicaCount: 1
auth:
  username: admin
  existingSecret: clickhouse-auth
  existingSecretKey: password
resources:
  requests:
    memory: 512Mi
  limits:
    memory: 2048Mi