generators:
  - helmChart.yml

configMapGenerator:
  - name: vector-sources
    namespace: vector
    files:
      - ./configs/sources/http_server_data_in.yml
    options:
      disableNameSuffixHash: true
  - name: vector-transforms
    namespace: vector
    files:
      - ./configs/transforms/classify_domain.yml
      - ./configs/transforms/route_by_domain.yml
      - ./configs/transforms/enrich_sensor.yml
    options:
      disableNameSuffixHash: true
  - name: vector-sinks
    namespace: vector
    files:
      - ./configs/sinks/console.yml
      - ./configs/sinks/sensor_to_kafka.yml
    options:
      disableNameSuffixHash: true

resources:
  - namespace.yml
  - kafka-credentials-for-vector.yml