role: "Stateless-Aggregator"
replicas: 1
serviceHeadless:
  enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: --placeholder--
      paths:
        - path: /
          pathType: Prefix
          port:
            number: 80
  tls:
    - secretName: vector-tls
      hosts:
        - --placeholder--

extraVolumes:
  - name: vector-sources
    configMap:
      name: vector-sources
  - name: vector-transforms
    configMap:
      name: vector-transforms
  - name: vector-sinks
    configMap:
      name: vector-sinks

extraVolumeMounts:
  - name: vector-sources
    mountPath: /vector/sources
  - name: vector-transforms
    mountPath: /vector/transforms
  - name: vector-sinks
    mountPath: /vector/sinks