- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create a Kafka namespace
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../namespace.yml"
        state: present
        apply: True
    - name: Install kafka credential secret
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../kafka-sasl-credentials.yml"
        state: present
        apply: true
    - name: Install Kafka from Helm and kustomize
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('kubernetes.core.kustomize', dir=playbook_dir + '/..', binary_path='/usr/bin/kustomize', enable_helm=True) }}"
