- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create the nginx-ingress-controller namespace
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../namespace.yml"
        state: present
        apply: True
    - name: Generate an additional values file from a template
      ansible.builtin.template:
        src: ./templates/generated-values.j2
        dest: ./generated-values.yml
    - name: Install nginx-ingress-controller from Helm and kustomize
      kubernetes.core.k8s:
        state: present
        namespace: nginx-ingress-controller
        definition: "{{ lookup('kubernetes.core.kustomize', dir=playbook_dir + '/..', binary_path='/usr/bin/kustomize', enable_helm=True) }}"
    - name: Remove generated additional values file
      ansible.builtin.file:
        path: ./generated-values.yml
        state: absent