image:
  repository: bitnamilegacy/nginx-ingress-controller
  tag: 1.13.1
defaultBackend:
  image:
    repository: bitnamilegacy/nginx
    tag: 1.29.1
kind: DaemonSet
daemonset:
  useHostPort: true
nodeSelector:
  node-role.kubernetes.io/control-plane: ""