global:
  domain: argocd.prod.rods.me

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostname: argocd.prod.rods.me
    tls: true
