apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: nginx-ingress-controller
name: nginx-ingress
repo: oci://ghcr.io/nginx/charts
releaseName: nginx-ingress-controller
namespace: nginx-ingress-controller
valuesFile: values.yml
