controller:
  kind: daemonset
  hostNetwork: true
  service:
    create: false
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  enableCustomResources: false
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Equal"
      value: ""
      effect: "NoSchedule"