type: route
inputs:
  - transactions_from_kafka_to_clickouse_remap
route:
  cc:
    type: vrl
    source: .subpath == "cc"
  car:
    type: vrl
    source: .subpath == "car"
  test:
    type: vrl
    source: .subpath == "test"
