apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-sources
  namespace: vector
  labels:
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/instance: vector
    app.kubernetes.io/managed-by: Helm