---
customConfig:
  api:
    enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: vector.rods.me
      paths:
        - path: (/|$)(.*)
          pathType: ImplementationSpecific
          port:
            number: 80
persistence:
  enabled: true
service:
  ports:
    - name: http-server
      port: 80
      protocol: TCP
containerPorts:
  - containerPort: 80
    name: http-server
    protocol: TCP
logLevel: "debug"
env:
  - name: KAFKA_AUTH_USER
    valueFrom:
      secretKeyRef:
        name: kafka-auth
        key: user
  - name: KAFKA_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: kafka-auth
        key: password
  - name: CLICKHOUSE_AUTH_USER
    valueFrom:
      secretKeyRef:
        name: clickhouse-auth
        key: user
  - name: CLICKHOUSE_AUTH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: clickhouse-auth
        key: password
extraVolumes:
  - name: vector-sources
    configMap:
      name: vector-sources
  - name: vector-sinks
    configMap:
      name: vector-sinks
extraVolumeMounts:
  - name: vector-sources
    mountPath: /vector/sources
  - name: vector-transforms
    mountPath: /vector/transforms
  - name: vector-sinks
    mountPath: /vector/sinks
args:
  - --config-dir
  - "/vector/"
image:
  base: "debian"
