resources:
  - ../../base
patches:
  - target:
      kind: Ingress
      name: redpanda-console
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: n8n.prod.rods.me
      - op: replace
        path: /spec/tls/0/hosts
        value: [n8n.prod.rods.me]
