- hosts: localhost
  become: false
  tasks:
    - name: Create a temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: awx
      register: awx_operator_dir
    - name: Checkout awx repo at a specific tag
      ansible.builtin.git:
        repo: 'https://github.com/ansible/awx-operator.git'
        dest: "{{ awx_operator_dir.path }}"
        version: 2.19.1
    - name: Create a k8s namespace for awx
      kubernetes.core.k8s:
        name: awx
        api_version: v1
        kind: Namespace
        state: present
    - name: Create doppler CRD for postgres configuration
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../postgres-configuration.yml"
        state: present
    - name: Create doppler CRD for awx admin password
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../awx-admin-password.yml"
        state: present
    - name: Create doppler CRD for awx secret key
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../awx-secret-key.yml"
        state: present
    - name: Copy awx configuration file to awx operator dir
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../awx.yml"
        dest: "{{ awx_operator_dir.path }}"
        mode: '0644'
    - name: Copy Kustomization file to awx operator dir
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../kustomization.yml"
        dest: "{{ awx_operator_dir.path }}"
        mode: '0644'
    - name: Install AWX with kustomize
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('kubernetes.core.kustomize', dir=awx_operator_dir.path, binary_path='/usr/bin/kustomize') }}"