apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: n8n
name: n8n
releaseName: n8n
repo: https://community-charts.github.io/helm-charts/community-charts
valuesFile: values.yml
namespace: n8n
