generators:
  - helmChart.yml

resources:
  - namespace.yml
  - postgres-configuration.yml
  - n8n-encryption-key.yml
  - n8n-license-activation-key.yml
  - n8n-task-runners-secret.yml

patches:
  - target:
      kind: ServiceAccount|ConfigMap|Service|Deployment|PodDisruptionBudget|Ingress|Secret
    path: patch-namespace.yaml
  - target:
      kind: Deployment
      name: n8n-worker|n8n
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: n8n-deployment
      spec:
        template:
          spec:
            containers:
            - name: n8n-task-runners
              image: n8nio/runners:2.8.3
              args: [python, javascript]