generators:
  - helmChart.yml

resources:
  - namespace.yml

patches:
  - target:
      kind: ServiceAccount
    path: patch-namespace.yaml
  - target:
      kind: ConfigMap
    path: patch-namespace.yaml
  - target:
      kind: Service
    path: patch-namespace.yaml
  - target:
      kind: Deployment
    path: patch-namespace.yaml
  - target:
      kind: PodDisruptionBudget
    path: patch-namespace.yaml
  - target:
      kind: Ingress
    path: patch-namespace.yaml