apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: n8n-encryption-key
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: n8n-encryption-key
  config: prd
  managedSecret:
    name: n8n-encryption-key
    namespace: n8n
    type: Opaque