main:
  extraEnvVars:
    - name: N8N_LISTEN_ADDRESS
      value: "0.0.0.0"
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: --placeholder--
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - --placeholder--