main:
  extraEnvVars:
    N8N_LISTEN_ADDRESS: "0.0.0.0"
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: --placeholder--
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - --placeholder--

# -- External PostgreSQL parameters
db:
  type: postgresdb

externalPostgresql:
  host: pg-af720c5-aware.j.aivencloud.com
  username: "avnadmin"
  port: 19581
  database: n8n
  existingSecret: postgres-configuration