log:
  level: debug
main:
  extraEnvVars:
    N8N_LISTEN_ADDRESS: "0.0.0.0"
    #DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: --placeholder--
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - --placeholder--

# -- External PostgreSQL parameters
db:
  type: postgresdb
  postgresdb:
    ssl:
      base64EncodedCertificateAuthorityFile: -|
        -----BEGIN CERTIFICATE-----
        MIIEQTCCAqmgAwIBAgIUNq+VjIvfa4KVlExuDi5od86JpHIwDQYJKoZIhvcNAQEM
        BQAwOjE4MDYGA1UEAwwvNGFiNDA0ZTItYTZmNC00MDY5LTgwNWUtOGFhOTJmOWQ5
        YmQ1IFByb2plY3QgQ0EwHhcNMjQwOTI5MTY1OTI4WhcNMzQwOTI3MTY1OTI4WjA6
        MTgwNgYDVQQDDC80YWI0MDRlMi1hNmY0LTQwNjktODA1ZS04YWE5MmY5ZDliZDUg
        UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAMRKaoPP
        doeEeom+IxYzIL9zIE0C14oVr1s0t+tVvmdLyxYJL3cXpCJEWpJ8hRVmKHSY1IDS
        yXS3cQtW+mSXy/huC8PAby6RKxkf8W2G6alSnnBrPnhs7KirBlcFhnYazEA2e/S/
        MinMAAlMbPuihj6XFPr7KccypdCPZyNb4Is72oldLgw7KrbxI/zo3W7DUVWKqUxc
        R7K00KDOrJo+Sjmuu+MvF81DIkluKeJdKPv0rvDGmEP8EIZe/7c5bWEIGk96wlg1
        YwHediKJNx6VxKCsDaeX9X46OvcjTsJeSSgl+TATNoxAF7UZuHont9dMmaLhPCf9
        QKhAMolIju5adA/5gaVKHeurrL+1uCI2kPGrIRyatJmmEy4fOjVZT7Sv26suTgLc
        EP6PbQ7IFItIa87tuip2VEMW64xGuzRT6iU/hWSN+bxQFauxoWHhyzpOgnn2HTOC
        jzCquXouCK6RMgdSIcYvDq+VH4KrkWp//zmHgDTdOwWcfr32nAr9MVuH3wIDAQAB
        oz8wPTAdBgNVHQ4EFgQUPwyV/cvTPLvhFZVlkfvAja7h1towDwYDVR0TBAgwBgEB
        /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAEsmPfpsHPLm2fD2
        HH5jfj6B2LFGrMTfaYn6Wqy6+AAsjSvVSzL/cgHwbyErQk99pVlouWITSsUzENS4
        geBl85gnv4PxwbNs5pMR1MzyHzsaN+uB+YOqajkDEIx9d1cNFNlRr95z1M4P4EUH
        /gufvDlLZGVGko6RbuZdoLmmtZldZyf6RDeNxTfML8so6aS6GTE8KiWip6LAO1m3
        bLDUbTfrzEkgC7oBsJ4ywFlDFim4pj26WwygZEpa5D3j0m+/gxPHT4MTNqx/vSYG
        1+sbFy/tcWYDoyMwkq7PZfHxcIxev4iLL5HVeuH/72PI/KA4NXO5h/YwIpo5JPCu
        /dTgphLis4dggu6y2XXhr6uN0q3Wf1KcVU6WnMFd8rYStPrieOju4YppmwoeaiBl
        Ty8Dw072HS8+cX8+voWnKrpZ+mxPCCf1vozIBDg0fW92McOUgBIKIg7N+4MFZbCt
        g65exadGqfrK9Asre/dFoN7r2ZjAlEejPqeSp+5uOekX4LexpA==
        -----END CERTIFICATE-----


externalPostgresql:
  host: pg-af720c5-aware.j.aivencloud.com
  username: "avnadmin"
  port: 19581
  database: n8n
  existingSecret: postgres-configuration