apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redpanda-certificate
  namespace: redpanda
spec:
  secretName: redpanda-console
  dnsNames:
    - redpanda.dev.rods.me
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-traefik-stage
