config:
  kafka:
    brokers:
      - kafka-broker-0.kafka-broker-headless.kafka.svc.cluster.local:9092
      - kafka-broker-1.kafka-broker-headless.kafka.svc.cluster.local:9092
      - kafka-broker-2.kafka-broker-headless.kafka.svc.cluster.local:9092
    sasl:
      enabled: true

extraEnvFrom:
  - secretRef:
      name: kafka-sasl-credentials

tests:
  enabled: false

secret:
  create: false

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: dev.rods.me
      paths:
        - path: /redpanda
          pathType: ImplementationSpecific
  tls:
    - secretName: redpanda-tls
      hosts:
        - dev.rods.me
