apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kafka-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: kafka-sasl-credentials
  config: prd
  nameTransformer: lower-snake
  managedSecret:
    name: kafka-secret
    namespace: kafka
    type: Opaque