image:
  repository: bitnamilegacy/kafka
broker:
  replicaCount: 3
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi
controller:
  replicaCount: 3
  persistence:
    enabled: false
service:
  clusterIP: None
sasl:
  client:
    users:
      - Cvky5GNmzT
  existingSecret: kafka-sasl-credentials
