- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Delete Cert Manager from Helm and kustomize
      kubernetes.core.k8s:
        state: absent
        definition: "{{ lookup('kubernetes.core.kustomize', dir=playbook_dir + '/..', binary_path='/usr/bin/kustomize', enable_helm=True) }}"
