- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../namespace.yml"
        state: present
        apply: True
    - name: Install RBAC for Traefik
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
    - name: Install Traefik Resource Definitions
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
    - name: Install RBAC for Traefik Ingress NGINX provider
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-ingress-nginx-rbac.yml
    - name: Install application from Helm and kustomize
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('kubernetes.core.kustomize', dir=playbook_dir + '/..', binary_path='/usr/bin/kustomize', enable_helm=True) }}"
