- hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create Namespace
      kubernetes.core.k8s:
        src: "{{ playbook_dir }}/../namespace.yml"
        state: present
        apply: True
    - name: Install application from Helm and kustomize
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('kubernetes.core.kustomize', dir=playbook_dir + '/..', binary_path='/usr/bin/kustomize', enable_helm=True) }}"
